services:
  # --- MINIO : DATA LAKE (S3 Storage) ---
  minio-job:
    image: quay.io/minio/minio
    container_name: minio_job
    ports:
      - "9000:9000"    # API S3
      - "9001:9001"    # Console UI
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # --- CONFIGURATION AUTOMATIQUE DES BUCKETS ---
  minio-job-init:
    image: minio/mc
    depends_on:
      - minio-job
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio-job:9000 admin password123) do 
        echo 'En attente de MinIO sur http://minio-job:9000...' && sleep 2; 
      done;
      /usr/bin/mc mb myminio/raw-data || true;
      /usr/bin/mc mb myminio/processed-data || true;
      /usr/bin/mc mb myminio/curated-data || true;
      echo '🚀 Buckets créés avec succès !';
      exit 0;
      "
  # --- DATA WAREHOUSE (PostgreSQL) ---
  postgres_dw:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_USER: user_dw
      POSTGRES_PASSWORD: password_dw
      POSTGRES_DB: job_data_warehouse
    ports:
      - "5432:5432"
    volumes:
      - dw_data:/var/lib/postgresql/data
  
  # --- PGADMIN : Interface Graphique pour PostgreSQL ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # <--- Tu accèderas à l'interface sur http://localhost:5050
    depends_on:
      - postgres_dw
  # --- AIRFLOW : Initialisation de la base et création de l'admin ---
  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow_db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@airflow_db/airflow_db
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
  # --- AIRFLOW : Base de données interne ---
  airflow_db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db

  # --- AIRFLOW : Webserver (L'interface pour voir tes DAGs) ---
  airflow_webserver:
    image: apache/airflow:2.7.0
    command: >
      bash -c "pip install selenium webdriver-manager beautifulsoup4 requests boto3 pandas psycopg2-binary sqlalchemy && airflow webserver"
    depends_on:
      airflow_db:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./pipelines:/opt/airflow/pipelines
      - ./processing:/opt/airflow/processing
      - ./data:/opt/airflow/data
      - ./scraping:/opt/airflow/scraping
      - ./database:/opt/airflow/database
      - ./config:/opt/airflow/config
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@airflow_db/airflow_db
      - _PIP_ADDITIONAL_DEPENDENCIES=pandas sqlalchemy psycopg2-binary boto3 selenium webdriver-manager beautifulsoup4 requests
      - PYTHONPATH=/opt/airflow
      - MINIO_ENDPOINT_URL=http://minio-job:9000
      - DATABASE_URL=postgresql://user_dw:password_dw@postgres_dw:5432/job_data_warehouse

  # --- AIRFLOW : Scheduler (Celui qui lance les scripts) ---
  airflow_scheduler:
    image: apache/airflow:2.7.0
    command: >
      bash -c "pip install selenium webdriver-manager beautifulsoup4 requests boto3 pandas psycopg2-binary sqlalchemy && airflow scheduler"
    depends_on:
      airflow_db:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./pipelines:/opt/airflow/pipelines
      - ./processing:/opt/airflow/processing
      - ./data:/opt/airflow/data
      - ./scraping:/opt/airflow/scraping
      - ./database:/opt/airflow/database
      - ./config:/opt/airflow/config
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@airflow_db/airflow_db
      - _PIP_ADDITIONAL_DEPENDENCIES=pandas sqlalchemy psycopg2-binary boto3 selenium webdriver-manager beautifulsoup4 requests
      - PYTHONPATH=/opt/airflow
      - MINIO_ENDPOINT_URL=http://minio-job:9000
      - DATABASE_URL=postgresql://user_dw:password_dw@postgres_dw:5432/job_data_warehouse

volumes:
  dw_data:
  airflow_logs:
  minio_data: